name: Daily News Briefing

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  run-briefing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests feedparser scikit-learn groq python-telegram-bot python-dotenv google-genai

      - name: Run pipeline
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          GUARDIAN_API_KEY: ${{ secrets.GUARDIAN_API_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py

      - name: Save briefing to docs folder
        run: |
          if [ ! -f briefing.txt ]; then
             echo "ERROR: briefing.txt was not generated. Pipeline failed."
             exit 1
          fi
          mkdir -p docs
          cp briefing.txt docs/briefing.txt